### ISSUE TITLE
Cluster 2 + n Nodes

### ISSUE THREAD

**Issue by seelenreiter** [vmstan/gravity-sync#136]
Hello Michael,

thank you for your great project !!!

I am thinking about a Pi-hole Cluster with WAN connectivity.

In my rooms, i am now running a pi-hole cluster with 2 nodes. 
I got 2 permanent VPN connections to my partens / p in law (?)
I'd like to install 2 more pi-holes at the remote networks syncing my pi-hole settings.

The main problem seems to be:

1. to handle more than 1 certificate (naming problem) on the master pi-hole

you could expand the key name with the mac address or guid (because of ipv6)

2. i am not sure what happens, if 2 nodes ar updating at the same time.

there could be a "busy semaphore" at the master pi-hole to pause other update scripts running with a random retry time.
that could cause a stop working on broken update processes. Maybe there could be a kind of time out on master pi-hole, cleaning the semaphore.....

best regards from germany
Ingo

**Comment by nh-mike** [comment]
Hi @seelenreiter 

While the project does not support this, I had a little think this morning on how this may be achieved. I expect that to add this into Gravity Sync itself would require a rather large overhaul of the project, and it would probably end up doing essentially the same thing as what I will describe here (although likely in a much more optimised manner).

If you treat your main Pi Hole as the secondary instance within Gravity Sync, you can rotate multiple remote Pi Holes with multiple configuration files.

Rather than calling Gravity Sync directly within Cron, you can call a script which will swap out configuration files and call Gravity Sync.

Of course, the problem becomes that if you do not sync the up to date Pi Hole on the first sync run, each Pi Hole after will be out of date except definitely the main Pi Hole and the last one in the sync run will be up to date.

Since the main one is up to date though, we can just do another pass of synchronisations, to bring all the other ones up to date.

You will want to create a directory somewhere, and fill it with various Gravity Sync configuration files, configuring the connection between both the main Pi Hole (as the Local Pi Hole) and each remote connection, all in their own individual configuration files. These files will be copied in place of the main configuration file before each Gravity Sync run.

Then, you must place this script on your filesystem somewhere, set it to executable, and then test it first (I do not have a >2 Pi Holes to sync up), and if it runs successfully then create an entry in your Cron.

Also, take note that this will move your backups (still within the same directory) for Gravity Sync's Primary instance (the remote instance)directory) so that for a config file named main.conf, the custom.list.push file will be named main.custom.list.push - as far as restoring backups, you're on your own in this regard.



	#!/bin/bash

	confsdir="/home/gravitysync/configs"
	gsdirpath="/home/gravitysync"

	for (( i=0; i<2; i++ ))
	do
		for file in ${confsdir}
		do
			cp ${confsdir}/${file} ${gsdirpath}/gravity-sync.conf

			${gsdirpath}/gravity-sync.sh

			mv ${gsdirpath}/backups/custom.list.push ${gsdirpath}/backup/`basename ${file} .conf`.custom.list.push
			mv ${gsdirpath}/backups/gravity.db.push ${gsdirpath}/backup/`basename ${file} .conf`.gravity.db.list.push
		done
	done

	rm ${confsdir}/${file} ${gsdirpath}/gravity-sync.conf

**Comment by seelenreiter** [comment]
FILE=/.../gravitysyncinprogress

while [ -f "$FILE" ] ;
do
      sleep 60
done

**Comment by seelenreiter** [comment]
Hi @nh-mike,

thank you for your replay.

there shouldn't be a problem to copy the whole gravity-sync settings to the 2rd pi. with the same ssh key (also coppied),
there will be no rights trouble.
(i would prefere a own ssh key for each backup pi. That shouldn't be a problem, too)

while the job is running on the backup node, there must be a way to prevent a 2nd script running at the same time.
Like a semaphore file "sync in progress" at the master pi. 

1. the gravity-sync.sh needs to check for the  semaphore file on start and just do pause for 60 secounds  and check again

I am not sure if the syntax is ok. 

`#Link to semaphorefile
FILE=/.../gravitysyncinprogress

# check if file exists
while [ -f "$FILE" ] ;
do

  # check fileage in secounds greater 600
  if [ [fileAge $FILE] -gt 600 ]
    
    #remove semaphore after 10 minutes (seems to be a broken sync prozess
    then rm $FILE
    
    #just wait a minute
    else sleep 60
  fi

done
`
and the function

`function fileAge
{
    local fileMod
    if fileMod=$(stat -c %Y -- "$1")
    then
        
        # return fileage in secounds
        echo $(( $(date +%s) - $fileMod ))
       
    else
        return $?
    fi
}
`



2. then, the gravity-sync.sh needs to create the semaphore file bevor sync and just remove it at any exit points.

**Comment by nh-mike** [comment]
This second script you are referring to, is this one of your own scripts that you have created? If so, may I ask what is the purpose for this script? If I can understand what it is you intend to do, then I may be able to assist you with this.

In your original question, you raised point number 2, where you said 

> 2. i am not sure what happens, if 2 nodes ar updating at the same time.

This is what the script I have provided previously will address. It would not be good to have more than 1 node being updated, and so we do them one after the other. In this way, we can keep track of which one is being updated, and no flags (semaphores) are required for this purpose.

**Comment by seelenreiter** [comment]
> This is what the script I have provided previously will address. It would not be good to have more than 1 node being updated, and so we do them one after the other. In this way, we can keep track of which one is being updated, and no flags (semaphores) are required for this purpose.

mea culpa, you are right.

your view is push from the master.
my view was pull from the backup 😉 as originaly prefered in the doc

**Comment by nh-mike** [comment]
That's right.

However, come to think of it, this method will still require more work.

GravitySync uses MD5 to keep track of which databases have changed. Simply, if the md5 is different to what it previously was, then the file has changed and needs to be synchronised.

I will have to look into how this works, and then incorporate rotating these MD5s into the script.

**Comment by nh-mike** [comment]
Hi @seelenreiter
I have updated my script in my original reply to account to allow for rotating the MD5 hashes.

You will need to create 2 directories in your GravitySync directory - one for keeping your config files, and one for keeping your MD5 files.

I expect this should work but I am unable to test it. Let me know whether this works for you.
