### ISSUE TITLE
Add as variable in conf file port to be used for rsync

### ISSUE THREAD

**Issue by xorguy** [vmstan/gravity-sync#14]
For systems where the default 22 is not used for SSH/rsync script must be manually edited to add correct port.

If it can be added to the conf file it will help a lot. For simple ssh connection port can be defined at ssh config file, but for rsync it is hardcoded.

Thanks for the tool!

**Comment by vmstan** [comment]
Great idea, surprised I missed that one when I went through and put in variables for everything else along the way. I've put it on the 1.4 code that should be pushed out very soon.

**Comment by vmstan** [comment]
I just published the 1.4 update. You should now be able to set `SSH_PORT='123'` in your `gravity-sync.conf` file to overwrite port 22 that's set in the script. It doesn't exist in the config file by default because I don't expect many people to use it. This should make it easily persistent after upgrades.

Please upgrade, test and let me know if it works for you.

**Comment by xorguy** [comment]
Hi, just tested and it works without a hitch. 

Thanks a lot!

**Comment by vmstan** [comment]
Fantastic
