### ISSUE TITLE
Can’t SSH Connect to primary Pi-hole on fresh gravity sync install

### ISSUE THREAD

**Issue by MirkoKas** [vmstan/gravity-sync#210]
Hi,

I‘m running Pi hole for a long time on my main Pi and just installed Pi hole on second Pi and want to use gravity sync to keep them in sync. 
Followed the wiki to install gravity sync and it worked without any problems on both pi. The configuration on the secondary pihole is the default. 
When I try the next step on the wiki (compare command) I get the error that the connection to the main Pi-hole can’t established. Don’t know what’s wrong because the ssh works as it should when established manually. 
is it because on both machines I have the the same SSH user ‚pi‘?

any help is appreciated.

**Comment by Trenta27** [comment]
I get the same. Configuration setup was great, but when trying to do a compare, it says connection refused. I already tried deleting the ssh keys on both ssytems to start fresh (no passphrase), but its not working. Not sure what I'm doing wrong as I can ssh into it from the secondary just fine.

**Comment by wojtashek** [comment]
Hi, I had same problem.
The cause of this problem is an incomplete configuration (for me it was caused by an invalid command when selecting advanced settings, although I entered "y" - most likely the letter case does matter)
To reconfigure, type the command **./gravity-sync.sh config**

pi@pihole2:~/gravity-sync $ **./gravity-sync.sh config**

Then see the configuration list. At the bottom, type 
**ENGAGE TRACTOR BEAM** 

This will re-configure. If you are not using a docker, select **N** (I got clean installation on Raspberry Pi)
Program will ask you some questions and create an ssh key, then you can connect and problem should be solved.
