### ISSUE TITLE
What is better than two piholes?

### ISSUE THREAD

**Issue by loaderladdy** [vmstan/gravity-sync#347]
I have 3 piholes running on raspberryOS. Ive been looking for a solution like this for a while as trying to keep rules in sync is a pain. I want to make sure I have a predictable environment for DNS blocking problem resolution. Have rules in sync across all three piholes is one part of the equation. My lab/home network uses AD DNS with forwarding to two virtual Kemp Free LoadBalancers and they in turn round robin to the three piholes, which use unbound for DNS resolution.

I suspect I can chain the sync for two and then the third relies on the second to be in sync.

but one primary to two plus secondary piholes, or multi-primary, a bit like a directory like Active Directory would be ideal

**Comment by accessiblepixel** [comment]
I had an idea about this, you could set up automation on the secondary PiHole install with gravity-sync to just `gravity-sync pull` (rather than doing an 'auto' sync) since then it will only take configuration from the primary, so you could do that on both 'secondary' systems, especially if you don't make changes to the secondary and tertiary, and setup different sync schedules, maybe one at 4 minutes and the other at 7?

Just an idea :)

Kind regards,
Jessica

**Comment by loaderladdy** [comment]
What a great idea Jessica. I'd not thought of doing it that way, and it makes total sense

Thank you

Pete
