### ISSUE TITLE
Not invoking GS after a pihole command 

### ISSUE THREAD

**Issue by Panja0** [vmstan/gravity-sync#44]
**Describe the Issue**
_It will also bring over the downloaded blocklist files after a pihole -g command is run to update blocklists on the primary, so you do not need to reach out to all your blocklist hosts for updates after syncing on the secondary._

I have setup 2 test Pihole servers at the moment and running GS on Pihole02.
When I do a `pihole -g` command on Pihole01 (or 02) it does not sync the blocklist.
So GS is not invoked after running the `pihole -g` command.

**Configuration:**
 - Debian 10
 - ESXi v7
 - OpenSSH
 - keypair
 - GS v1.8.3
 - Pihole v5

**Additional Context**
Running a GS manually or via Cron works without problems.

**Comment by vmstan** [comment]
That is working as expected. The documentation might need to be worded differently, but what that means is if you do the pihole -g, once you sync with GS, you will have all the same contents of the actual blocklist on the other side. You don't have to run the pihole -g on the secondary for it to have the same content. Not that it will automatically kick off a sync. That would likely require modification to the Pi-hole code which I specifically do not want to to do.

**Comment by Panja0** [comment]
Ok, I misunderstood the documentation than. My bad!
So if I understand correctly after I do a GS on Pihole02 (pulling from Pihole01) I need to do a pihole -g on Pihole02 as well to have everything working?

**Comment by vmstan** [comment]
No. When the primary does a pihole -g, the gravity.db file there is loaded up with the content of the block list download. What Pi-hole actually does is create a new file, load it up, and then switches it for the new one and reloads DNS services.

When Gravity Sync is run, it's essentially doing the same thing, except instead of building a new gravity.db it's copying the one from the primary. The same DNS services are restarted once the copy has happened. The result is the exact same gravity.db in both places with the same block list contents. 

No need for additional pihole -g at the secondary site.

**Comment by Panja0** [comment]
Wicked! Clear now. :-)

**Comment by nicedevil007** [comment]
may I reopen this issue?

I recently installed the script and everything seems to work fine except the pihole -g 
If I add a complete fresh adlist to the main pihole and do the initial pihole -g via webUI and then check my 2nd pihole for the update a couple minutes later I can only find the new blocklist there but the amount of blocked domains is still the one from default installation.
