### ISSUE TITLE
Gravity Sync Auto

### ISSUE THREAD

**Issue by carlowisse** [vmstan/gravity-sync#454]
To debug this issue without just running random commands, I was wondering if I had to run `gravity-sync auto` on both nodes for the auto sync to work? Or do I just run it on the master?

**Comment by bblboy54** [comment]
I actually have the same question for a different reason. 

My primary pi-hole is running on a VM on my Proxmox server and my secondary is running on a Raspberry Pi 1 (reasoning is the proxmox server only has battery backup for a short time while the pi can run for hours with my router).  Since the VM has more processing power my thinking is that maybe I should only configure auto on the primary pi-hole to save processing power on the RasPi but I'm not sure if there is a downside to only running on a single node.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.
