### ISSUE TITLE
Cron "bug" after updating from 1.8.3 to 2.0.0

### ISSUE THREAD

**Issue by Panja0** [vmstan/gravity-sync#50]
> New installs will use the smart function by default. Existing users who want to use this new method as their standard should run ./gravity-sync.sh automate function to replace the existing automated pull with the new Smart Sync.

**Describe the Issue**
After updating to v2.0.0 I did a `./gravity-sync.sh automate` to change to the new standard.
Instead of replacing the excisting cron job it adds a new one. Resulting in a double job now.

`crontab -l  `              
`*/15 * * * * /bin/bash /home/pi/gravity-sync/gravity-sync.sh pull > /home/pi/gravity-sync/gravity-sync.cron`
`*/15 * * * * /bin/bash /home/pi/gravity-sync/gravity-sync.sh > /home/pi/gravity-sync/gravity-sync.cron`

**Configuration:**
 - Debian 10
 - ESXi v7.0
 - OpenSSH
 - keypair
 - GS 2.0.0
 - Pi-hole V5.0

**Workaround:**
I did a `crontab -e` and removed the double line manually.

**Comment by vmstan** [comment]
Yep, in prior versions I had it looking for `.sh pull` in the existing code to remove it, because that was unique enough, but in 2.0 it switched to looking for the name of the full GS script based on a variable and I still had the single quote mark around the variable name so it wasn't getting properly parsed. Switched to double quotes and published as 2.0.1.

**Comment by Panja0** [comment]
Updated to v2.0.1 and can confirm that it's working now, as advertised! Thanks for the quick fix!
