### ISSUE TITLE
gravity.db ownership

### ISSUE THREAD

**Issue by tomtom-77550** [vmstan/gravity-sync#99]
**Describe the Issue**
once installed gravity-sync on the primary pi.hole, gravity.db is no longer available and i get a ownership fail in the gravity-sync.sh. it seems also that once installed the primary becomes the secondary and secondary becomes primary. the blacklist and white liste can only be updated or modified from the secondary pi.hole

in my config, Primary pi.hole is 192.168.2.2
Secondary pi.hole is 192.168.2.3

**Screenshots**
![Capture d’écran 2020-10-07 à 12 41 02](https://user-images.githubusercontent.com/72498825/95320916-85efc080-089a-11eb-92b6-963d475fba83.png)
this is from my primary pi.hole
![Capture d’écran 2020-10-07 à 12 43 39](https://user-images.githubusercontent.com/72498825/95321103-db2bd200-089a-11eb-8a24-bbc1e0b27005.png)
![Capture d’écran 2020-10-07 à 12 42 57](https://user-images.githubusercontent.com/72498825/95321121-e0891c80-089a-11eb-9221-d031a5fc7dea.png)

i can only update the secondary pi.hole and make changes to whitelist blacklist on the secondary pi.hole. still, running the gravity sync.sh will update the primary pi.hole fine. 

For some reason, gravity.db file has changed ownership and switch from user pihole to root. 

**Configuration:**
 - OS for Primary/Secondary: [e.g. Ubuntu/DietPi]
both running raspbian OS Lite Buster version 10
 - Platform for Primary/Secondary: [e.g. VMware ESXi/Raspberry Pi 4]
Both on raspberry pi3b+
 - SSH Server/Client: [e.g. OpenSSH/Dropbear]
default in raspbian OS
 - SSH Authentication: [e.g. Keypair, Password]
is Keypair
 - Gravity Sync Version: [e.g. 1.7.6]
gravity sync version is 2.2.3
 - Pi-hole Versions: [e.g. v5.0]
both on pi.hole version 5.1.2

**Additional Context**
Add any other context about the problem here. If you have any advanced flags set in your `gravity-sync.conf` please list them here.

no advanced flags set

**Comment by tomtom-77550** [comment]
so what i did is from primary pi.hole run sudo chown pihole:pihole gravity.db seems back to normal now and i can update again whitelist on primary. running gravity-sync.sh from secondary will make changes well.  something is probably not clear in the install instructions that lead to a mistake.

**Comment by vmstan** [comment]
When you ran the first sync, were there any errors in the interface?

**Comment by vmstan** [comment]
This should be fixed in 3.0

**Comment by kzaoaai** [comment]
just had the same issue with the latest version. fixed by chown.

Configuration:

OS for Primary/Secondary: [e.g. Ubuntu/DietPi]
Primary on Docker Arm; Secondary on raspbian OS Buster
Platform for Primary/Secondary: [e.g. VMware ESXi/Raspberry Pi 4]
Primary on RPi4, Secondary on RPi1b+
SSH Server/Client: [e.g. OpenSSH/Dropbear]
default
SSH Authentication: [e.g. Keypair, Password]
Password
Gravity Sync Version: [e.g. 1.7.6]
gravity sync version is 3.1.1
Pi-hole Versions: [e.g. v5.0]
both on pi.hole version 5.1.2
Additional Context

**Comment by vmstan** [comment]
Was it a push or pull that last run that locked it up? (Where was the last change made?)

**Comment by kzaoaai** [comment]
I think it was a pull. Here are the last few lines:

`[✓] Performing Backup of Remote gravity.db
[✓] Performing Backup of Local gravity.db

[✓] Copying gravity.db from 192.168.1.198
[✓] Pushing gravity.db to 192.168.1.198
[✓] Setting Permissions on gravity.db
[e] Setting Ownership on gravity.dbchown: invalid user: ‘named:docker’
[✗] Setting Ownership on gravity.db`

It's worth mentioning that I haven't had that error since I set the permissions of the etc folder on the Secondary (docker) to the ssh user's.

**Comment by vmstan** [comment]
OK, that makes more sense, I think I need evaluate how I look at file permissions for Docker setups.

**Comment by kzaoaai** [comment]
Sounds good, thanks for your great work. (PS i had one edit above, it's the primary (docker) not secondary (raspbian))

**Comment by kzaoaai** [comment]
moved my secondary to a docker as well, and now this cannot work due to permissions. Both Pi's have the same users and same directories.
`[i] Gravity Sync 3.1.1 Executing
[✓] Importing gravity-sync.conf Settings
[✓] Evaluating Arguments: SMART Requested
[i] Targeting pi@192.168.1.198
[✓] Validating SSH Client on RPi3 (OpenSSH)
[✓] Validating RSYNC Installed on RPi3
[✓] Validating Gravity Sync Folders on RPi3
[✓] Validating Pi-hole Configuration
[✓] Validating SQLITE Installed on RPi3
[✓] Validating Connection to 192.168.1.198
[i] Starting SMART Analysis
[✓] Analyzing gravity.db on 192.168.1.198
[✓] Analyzing gravity.db on RPi3
[!] Differenced gravity.db Detected
[✓] Analyzing custom.list on 192.168.1.198
[✓] Analyzing custom.list on RPi3
[!] Differenced custom.list Detected
[!] Replication Required
[!] Both gravity.db Have Changed
[!] Secondary gravity.db Last Changed
[✓] Performing Backup of Remote gravity.db
[✓] Performing Backup of Local gravity.db
[✓] Copying gravity.db from 192.168.1.198
[✓] Pushing gravity.db to 192.168.1.198
[✓] Setting Permissions on gravity.db
[e] Setting Ownership on gravity.dbchown: invalid user: ‘named:docker’
[✗] Setting Ownership on gravity.db`

**Comment by krzysiek-kurek** [comment]
Replace 
>
FILE_OWNER='named:docker'
RILE_OWNER='named:docker'

to
>
FILE_OWNER='999:999'
RILE_OWNER='999:999'

sync will adress gravity.db ownership by UID:GID instead names that might differ on various distro.
